### ISSUE TITLE
fix(api/models): problems in CategoriesModel

### ISSUE THREAD

**Issue by daviddcordoba** [RodrigoSpano/pigCommander_back#3]
``$ npm run start:dev

> back@1.0.0 start:dev
> nodemon src/app.ts

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/app.ts`
C:\Users\David\Desktop\pigCommander_back\src\model\CategoriesModel.ts:5
const CategoriesModel = sequelize.define<Model<CategoriesModelBase>>(
                                  ^
TypeError: Cannot read properties of undefined (reading 'define')
    at Object.<anonymous> (C:\Users\David\Desktop\pigCommander_back\src\model\CategoriesModel.ts:5:35)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\Users\David\Desktop\pigCommander_back\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\David\Desktop\pigCommander_back\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\David\Desktop\pigCommander_back\src\model\index.ts:1:1)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lucasgrav** [comment]
try deleting the node_modules and reinstalling the dependencies

**Comment by benjapadilla1** [comment]
Try putting more effort into it and handle it over for today please
